baseURL = "baseURL = "https://hw4090-create.github.io/Netizen-s-Guide-to-Preserving-Github-Repositories/"
languageCode = 'en-us'
title = 'Netizen of Guide to Preserving Github Repositories'
theme = "hugo-book"

enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  BookTheme = 'auto'      
  BookToC = true         
  BookSection = 'docs'   
title   = "Netizen's Guide to Preserving Github Repositories"
theme   = "hugo-book"

defaultContentLanguage         = "en"
defaultContentLanguageInSubdir = true

[params]
  BookSection = "docs" 
  BookTheme   = "auto"
  BookSearch  = true

[languages]

  [languages.en]
    languageName = "English"
    weight       = 1
    contentDir   = "content/en"

  [languages.zh]
    languageName = "ä¸­æ–‡"
    weight       = 2
    contentDir   = "content/zh"
>>>>>>> ven-based
